name: Build maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
      
  upload:
   
    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout ğŸ™ƒ
       uses: actions/checkout@v3
       
     - name: Set up JDK 8 ğŸ› 
       uses: actions/setup-java@v3
       with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
        
     - name: Setup Maven 3.8.6 ğŸ”®
       uses: stCarolas/setup-maven@v4.3
       with:
        maven-version: 3.8.6
        
     - name: Build Jar files ğŸ“
       run: mvn package clean
       
     - name: Upload files â˜
       uses: actions/upload-artifact@v3
       with:
        name: PixelMOTD Plugin
        path: ./target/PixelMOTD*
        retention-days: 30
